### ISSUE TITLE
[Feature] Typing indicators 

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#11]
**Is your feature request related to a problem? Please describe.**
The back end has basic support for typing status indicators via websocket events. This needs front end implementation.

**Describe the solution you'd like**
When in a chat view, there should be some sort of indication if another user is typing. This could be a simple animation at the bottom of the screen, but as with anything else there are probably creative ways to express this visually.

**Comment by heisler98** [comment]
There are some rudimentary typing indicators.
