### ISSUE TITLE
[Feature] Global mute

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#12]
**Is your feature request related to a problem? Please describe.**
The back end has support for a "global mute" feature. This is a simple toggle that the user should be able to set in their settings.

**Describe the solution you'd like**
In the settings, a user can either set
- No mute: Notify me of every message sent in a chat
- Muted: Only notify me of a message if I am tagged

**Additional context**
This functionality will at some point in the future be expanded further to allow for granular control in specific chats.

**Comment by heisler98** [comment]
Note to self: Also check if we can grab the device's Focus status.

**Comment by colingoodman** [comment]
Providing more specific information here. `/users/mute` endpoint has a query parameter `mute` that is an integer. 0 means mute is off, any number greater than 0 means mute is on. 

The reason why is this isn't a boolean value is because I envision granular control eventually. A `1` mute level might be receiving push notifications for being tagged, whereas a `2` might be no push notifications at all. You don't need to worry about this for now.

**Comment by heisler98** [comment]
Mute works.
