### ISSUE TITLE
[Bug] Bucket(?) issues

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#14]
**Describe the bug**
I received several push notifications for messages that I am unable to view when opening the app without manually refreshing.

**Approximate time and date of bug**
May 22 2023 9:51AM Mountain

**To Reproduce**
Receive a message, open app to view, find it is not present even after restarting the app several times. A hard refresh while within the app (pulling down while viewing the list of chats) did yield all of the messages.

**Comment by heisler98** [comment]
Rebuilt bucket loading. Opted for non-async, non-lazy scrolling. Sacrificed performance for the opportunity to test the loading system. Preliminarily, it is testing fine. Scrolling is just slightly less of a bitch.

**Comment by colingoodman** [comment]
So far things are loading on app start better; I don't need to refresh/restart anything. Scrolling is still poor.

**Comment by heisler98** [comment]
Note to self: I could do a local query for buckets instead of the list of messages. That would imply a Bucket reducer that managed a section (async loading!), and a Message reducer for each element in that bucket. 

I really thought that was a good idea when I was laying in the sun, but I am now wondering how that helps my problem...

**Comment by heisler98** [comment]
I've almost proven the scrolling issue is not the bucket system, but the images. See issue #19.

**Comment by colingoodman** [comment]
> So far things are loading on app start better; I don't need to refresh/restart anything. Scrolling is still poor.

Found just now that this is false. Just had to hard refresh to see a new message.

**Comment by heisler98** [comment]
Not surprising. The diffing algorithm is touchy at best. What's likely is that it was going to load the message eventually, just not on an appropriate timetable. 

This is my next best idea:

- Move messages to an in-memory store (which would require an abstraction out of Core Data)
- Persist only the latest bucket of messages(?)
- Load older buckets by the content offset of the scroll view 
- Implement this:
> I could do a local query for buckets instead of the list of messages. That would imply a Bucket reducer that managed a section (async loading!), and a Message reducer for each element in that bucket.

**Comment by heisler98** [comment]
Eh, it's all sorts of fucked up. Ditched view-data for MVVM. Seems to work alright in preliminary testing. Massive message volume will lead to missing message bugs, between latency, client-side web socket queue, and Sequoia's high message response times. There's no good way around that right now.

**Comment by colingoodman** [comment]
The original issue in this ticket has been resolved, though FWIW bucket loading is still whacky. Sometimes only a couple messages will appear in a room, sometimes it takes awhile to load any messages at all, etc.

Let me know what of this stems from server side issues if necessary.
