### ISSUE TITLE
[Bug] Image viewing is difficult and unintuitive

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#15]
**Describe the bug**
Tapping an image in a message to get a closer view yields multiple issues. First, the image is zoomed in. Second, zooming out or panning is buggy and the jittery. 

**Expected behavior**
When viewing an image, the image should not be zoomed in / it should fit the screen in scale appropriately. Panning and zooming should be smooth and reliable.

**Comment by heisler98** [comment]
Implemented a different image viewing experience. Reopen this issue if the problems persist.

**Comment by heisler98** [comment]
Image doesn't appear half the time. Oh joy.

**Comment by heisler98** [comment]
I think I fixed that. `await` wasn't `awaiting` the way I thought it would. Coming in the next build.

**Comment by heisler98** [comment]
Images are woke now
