### ISSUE TITLE
[Bug] Issues sending photo via camera

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#16]
**Describe the bug**
Image attachments via camera may or may not send correctly.

**Approximate time and date of bug**
May 22 2:55 PM Mountain

**To Reproduce**
1. Select option to add an image to a message
2. Select the camera option 
3. Take a photo and confirm
4. Send message
The red ! flickers a bunch even after restarting the app. I'm not actually certain if the message ever sent.

**Expected behavior**
Image should send as any other.

**Additional context**
Unsure if adding text to the message changes the outcome.

**Comment by colingoodman** [comment]
Update: confirmed with John that the message did not go through, though I can still see it on my end.

**Comment by heisler98** [comment]
I cannot replicate the above issue exactly, so I figure that it had to do with a flakey/non-existent/high-latency socket connection. I have not tested image resend, so it's possible that tapping the red ! does not resend the image properly.

**Comment by heisler98** [comment]
I implemented a rudimentary image-send status system. Now they won't fail silently. If they fail, it's because either: 
a) The upload failed (throws 413 probably because image size is >25MB)
b) The sockets aren't connected/authenticated

**Comment by heisler98** [comment]
I've been able to send images via camera fine. Reopen if issue persists.
