### ISSUE TITLE
[Feature] [Hunter] Video support

### ISSUE THREAD

**Issue by heisler98** [tiberloop/squidchat-issues#17]
Video support involves: 

1) Downsampling
2) Upload
3) Distinguishing a photo file from a video file upon download

Big problem: Alamofire won't tell me the content-type in the response header, but Postman proves that it's there.

**Comment by colingoodman** [comment]
I'd imagine that video (and image) processing is mostly my responsibility. We could have a hard limit to how large file uploads can be. I could try to zip large files that are rarely accessed. I could also try to scale videos smaller before storing.

**Comment by heisler98** [comment]
@colingoodman We probably should both downsample - me from the get-go so the upload times are shorter. Obviously the 25MB limit I implemented is far too high for images. Constructing a video size limit will be fun. Maybe I can automatically chop up a long video into chunks.

**Comment by colingoodman** [comment]
Perhaps something like this could be used for video uploads: https://en.m.wikipedia.org/wiki/GStreamer

I plan to use it for doing any video conversions (changing resolution, for example) in the back end.

There are probably a lot of ways to pass video up that aren't just packaging them in API requests.
