### ISSUE TITLE
[Bug] Large images crash squidchat

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#18]
**Describe the bug**
John uploaded (what I assume is) a high resolution image he took with his camera

**Approximate time and date of bug**
4:34 mountain may 25

**To Reproduce**
Upload a gigantic image. Attempt to use the app

**Logs**
I can email if needed.

**Additional context**
I tried to record a video of the lag but the screen recorder crashed or something. The performance really wrecked my phone.

**Comment by heisler98** [comment]
Send me the logs and let me know the image ID so I can look at it on the server.

**Comment by heisler98** [comment]
I assume Kingfisher blows a gasket trying to display large images. I'll implement a downsampler before upload to take care of that nonsense.

**Comment by heisler98** [comment]
Updates will be available in issue #19.
