### ISSUE TITLE
[Bug] Duplicate Messages

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#22]
**Describe the bug**
Sometimes when I send a message it displays twice instead of once. This is uncommon and I have not found any way to reliably replicate it.

**Additional context**
This could obviously be a variety of problems caused by either of us, perhaps your front end overcompensating for my back end by slow.

**Comment by heisler98** [comment]
That’s really not surprising, I imagine it’s a race condition between the
client importing the message and the server emitting it back to the client.
That whole system needs some TLC.

**Comment by colingoodman** [comment]
My message just showed up 3 times. The UI is really trigger happy. I also received a message twice from another person, meaning messages from different people are being duplicated.

**Comment by heisler98** [comment]
Gonna replace it soon with the system that was in Squidchat v0.1

**Comment by colingoodman** [comment]
Still seeing this occasionally, build 69.

**Comment by heisler98** [comment]
Nightmare! Message send queue had a bug that I cleared. Keep me up to date on whether you see this again.
