### ISSUE TITLE
[Feature] shared typing notifications

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#25]
I love love love the funny typing notifications. Its an easy way to add a lot of personality, and we should have as many unique messages as we can think of. I see the obvious inspiration from Carrot and approve 110%

However, I think to improve the interactivity of this we should make them consistent across devices. That way, everyone in a room will see "John is typing a fucking novel" and be able to share that experience in the moment. Currently it's entirely unique to the device and thus the impact is limited to one person.

The functionality of this would be shifted to the back end and I would emit the funny message so its consistent everywhere.

Let me know thoughts.

**Comment by heisler98** [comment]
That’s funny yeah let’s do it

**Comment by colingoodman** [comment]
I have pushed a first draft for this to sequoia. Added a `message` field to typing events. I will consider trying to track who is actively typing in a room to make these smarter, such as by having messages that involve more than one user. In the meantime, feel free to just use "X and Y are typing" or "multiple people are typing" etc

**Comment by colingoodman** [comment]
I also think it would make sense to display the typing notification above the user's keyboard so they can see what everyone else is seeing.

This might be messy, but it would keep them in on the joke that everyone else is seeing.

**Comment by heisler98** [comment]
What does "display the typing notification above the user's keyboard" mean? It is above the keyboard right now.

**Comment by colingoodman** [comment]
> What does "display the typing notification above the user's keyboard" mean? It is above the keyboard right now. 

Not if I am the one typing. I am trying to say that the typing message should display for everyone, including the user that is typing. That way they are also in on the joke

**Comment by heisler98** [comment]
Ohhhhh lol

**Comment by heisler98** [comment]
Done, need to test. The logged-in user's typing status should appear if no one else is typing. Other people typing takes precedence.

Note, that if any typing statuses contain profanity, Apple requires a Profanity opt-in.
