### ISSUE TITLE
[Bug] Image can cause message text to be off screen

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#26]
John uploaded a wide image along with some text. I cannot read the text because both it and the image are cut off the screen.

![image](https://github.com/tiberloop/squidchat-issues/assets/29467620/91cdbb3e-e64e-4137-b086-7863da7c8a30)

**Comment by heisler98** [comment]
I forgot to fix that 😂 I’m on it

**Comment by heisler98** [comment]
Done, in testing.
