### ISSUE TITLE
[Feature] Delay message loading animation

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#28]
This is probably on your to-do list, but I would like the round spinny loading thing that appears next to messages (upon sending) to be delayed 1-2 seconds. Since we now have a decent level of trust that a message will go through quickly, you could only display the load animation if its taking awhile for a particular message to send.

The end result will be the app "feeling" much faster since there is less of a perceived latency.

**Comment by colingoodman** [comment]
Bump

**Comment by heisler98** [comment]
😂

**Comment by heisler98** [comment]
Will implement little tiny checkmarks like Signal or something

**Comment by heisler98** [comment]
Done.
