### ISSUE TITLE
[Feature] Endpoints changing

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#29]
File endpoints are being changed to make room for more features. The following needs to be updated for use with the latest sequoia commit:

`/{file_id}/avatar` -> `/file/{file_id}/avatar`
`/{file_id}` -> `/file/{file_id}`

**Comment by heisler98** [comment]
This is the current endpoint structure:
<img width="488" alt="Screen Shot 2023-06-26 at 11 25 10 PM" src="https://github.com/tiberloop/squidchat-issues/assets/4079378/588655c8-a468-446e-a128-3b22fdd12343">

Are you saying it will become:

`/files/file/{file_id}/avatar`
`/files/file/{file_id}`

And did the file upload endpoint change to `files/file`?

**Comment by colingoodman** [comment]
Here is a screenshot of the new endpoints

![Screenshot 2023-06-27 at 7 20 13 AM](https://github.com/tiberloop/squidchat-issues/assets/29467620/c5feb0df-93a1-44ef-ab7d-ecc2f33daf05)

**Comment by heisler98** [comment]
Done.
