### ISSUE TITLE
[Bug] Password change fails successfully 

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#3]
**Describe the bug**
Attempting to change a user's password in the settings yields "password change was a success" yet it fails and I am only able to log in with my old password.

**Approximate time and date of bug**
~8:56AM mountain time may 17 2023

**Comment by heisler98** [comment]
I currently believe this is a Sequoia issue. See [Sequoia issue 30](https://github.com/colingoodman/sequoia/issues/30) and let me know if I need to change anything.

**Comment by heisler98** [comment]
**I will need to update Strongbox with the new password after the PUT becomes successful, else a manual logout will be required.**

**Comment by colingoodman** [comment]
A fixed has been pushed in the latest sequoia commit.

**Comment by heisler98** [comment]
Seems to work as intended. Password change modifies the client keychain appropriately. Pull to refresh would be all that's required at most.
