### ISSUE TITLE
[Feature] Replies

### ISSUE THREAD

**Issue by DonnyShits** [tiberloop/squidchat-issues#33]
*I know this might be further down development but having to @ people everytime for a response is tedious since in the time you want to respond , there might be 10+ messages in the way and you don't wanna re-explain what you're responding to*

**Comment by colingoodman** [comment]
@heisler98 I actually already partially implemented this. I will finish this up soon. There is a field `reply_to` for messages that takes a message identifier.

**Comment by heisler98** [comment]
Looks like this is a go. We want to implement tap-to-scroll.
