### ISSUE TITLE
[Bug] Only DMs work || Socket client handshakes slow/nonexistent

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#4]
**Describe the bug**
I have sent messages in both my DM with @heisler98 and the group chat "goat" with split results; the DM messages send fine while I am unable to send any messages in goat.

**Approximate time and date of bug**
Before 9AM mountain on may 17

**To Reproduce**
Send message in a DM: good
Send a message in a group chat: failure

**Screenshots**
![image](https://github.com/tiberloop/squidchat-issues/assets/29467620/20da5b50-4ee0-4a9d-92f3-e8108cee4c52)

**Additional context**
It is unknown whether I can receive messages via WS. As shown in the screenshot, previous messages from the DB loaded fine.

**Comment by heisler98** [comment]
Colin's log says this
`2023/05/17 14:25:55:861  Send message threw error. Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={NSDescription=Software caused connection abort}`
Never seen it before and don't know what it means.

**Comment by heisler98** [comment]
Pretty sure I've determined all message-send-failures today are caused by Apple prematurely terminating the NSURLSessionTask. I implemented a hack that is in testing and is currently working. If we experience further issues, check `AppCore.phaseBecameInactive` and the accompanying SO link.

**Comment by heisler98** [comment]
Getting a quick connect to sockets has been cumbersome with my current socket client implementation. Considering major revisions. It is currently patched and operating mildly successfully. I'm (maybe) noticing handshake latency on first-init from dead state, but wake-from-background seems very zippy. Not sure how zippy once the cached token is expired.

**Comment by heisler98** [comment]
The client generally tries to stay connected, does a half-assed job. Sequoia has trouble responding to messages while on high loads (Sequoia issue [#33](https://github.com/colingoodman/sequoia/issues/33))
