### ISSUE TITLE
[Bug] No push notifications

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#5]
**Describe the bug**
Hunter sent me some messages in a DM and I did not receive any push notifications.

**Approximate time and date of bug**
Before 9AM mountain on May 17

**Additional context**
I have sporadically received push notifications from sequoia while Hunter was doing development, so the back-end mechanism for such most likely works.
1. Verify that the mechanism for storing APNS tokens works properly.
2. Check env vars are set correctly in the docker container
3. Check that we are using the correct environments with APNS (dev vs prod)

**Comment by heisler98** [comment]
The enviro vars did not change and Sequoia used to say this:
`
Attempting to send push notifications.
BIG LONG LIST OF PUSH NOTIFICATION ATTEMPTS THAT SUCCEEDED OR FAILED
`
Now it just says this:
`Attempting to send push notifications.`

**Comment by heisler98** [comment]
That probably means my APNS token submission isn't working.

**Comment by heisler98** [comment]
APNS token submission is working – no APNS notifications. ~Going to check the key and reboot the server. Possibly a server problem. Rolling Sequoia to the latest commit now that we know it was always working fine.~ Haven't slept, forgot that Colin said that APNS tokens weren't being persisted to the DB.

**Comment by colingoodman** [comment]
Should be working fine now following the latest sequoia commit 👍
