### ISSUE TITLE
[Bug] DM names are changing

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#6]
**Describe the bug**
"Hunter" turned into "Dorian"

**Approximate time and date of bug**
Just after 9AM mountain time on May 17

**To Reproduce**
Unsure if I did anything to trigger this issue.

**Expected behavior**
"dorian" should say "hunter" as it is the DM for hunter and not dorian.

**Screenshots**
![image](https://github.com/tiberloop/squidchat-issues/assets/29467620/46d245bb-059e-4171-b7c1-6e03065e1622)

**Additional context**
Unsure if this issue will persist with other chats or DMs.

**Comment by heisler98** [comment]
Not functionally encumbering and since message avatars & names appear correctly, low-priority. Pull down to refresh on the rooms tab and the room should rename itself correctly. See [Sequoia issue #29](https://github.com/colingoodman/sequoia/issues/29)

**Comment by heisler98** [comment]
This issue is also happening with messages appearing as the wrong user. App-wide user entity relationship issue.

**Comment by heisler98** [comment]
Messages appearing as the wrong user occurring because of a race condition between the local message store, WS message import,  and the stacking code. Eliminated frontend stacking in favor of [Sequoia issue 22](https://github.com/colingoodman/sequoia/issues/22).

**Comment by heisler98** [comment]
Cannot yet replicate the DM-appearing-as-wrong-name issue. It may be a on-first-init problem...?

**Comment by heisler98** [comment]
Replicated the issue after logout. At least 4 members in DMs where API says only 2. Suspect issue with deleting the persistent store. First will try refactoring to delete all entities through CoreStore.

**Comment by heisler98** [comment]
Did logout/login 2x, then did app-delete and fresh-install. Suspicions confirmed – multiple persistent store files had overlapping Core Data z-indices. Destroying entities via CoreStore eliminated this issue so far. Will keep an eye.

**Comment by heisler98** [comment]
14 hours in, no sign of this problem remaining.
