### ISSUE TITLE
[Feature] Profiles

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#9]
**Is your feature request related to a problem? Please describe.**
Profiles. I should be able to tap a profile or whatever and see details on a person in a separate view.

**Comment by heisler98** [comment]
Ok, done. You see their avatar and their username and you can tap their avatar to see it bigger, and download it. Currently there's no documented way to set any other fields on a user object (name, email, etc.) so there's not much information to report there. 

Eventually will implement a DM button and shared room list and online status and all that shit but that's not a terribly high priority.
